<?php
/**
 * Extended User Profile
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright       The XOOPS Project http://sourceforge.net/projects/xoops/
 * @license         GNU GPL 2 (http://www.gnu.org/licenses/old-licenses/gpl-2.0.html)
 * @package         profile
 * @since           2.3.0
 * @author          Jan Pedersen
 * @author          Taiwen Jiang <phppp@users.sourceforge.net>
 * @version         $Id: xoops_version.php 13016 2015-03-15 18:21:22Z timgno $
 */

/**
 * This is a temporary solution for merging XOOPS 2.0 and 2.2 series
 * A thorough solution will be available in XOOPS 3.0
 *
 */
$modversion = array();
$modversion['name'] = _MI_PROFILE_NAME;
$modversion['version'] = 1.87;
$modversion['description'] = _MI_PROFILE_DESC;
$modversion['author'] = "Jan Pedersen, Taiwen Jiang, alfred, Wishcraft";
$modversion['credits'] = "Ackbarr, mboyden, marco, mamba, trabis, timgno, etc.";
$modversion['help']        = "page=help";
$modversion['license']     = "GNU GPL 2.0 or later";
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['image'] = "assets/images/logo.png";
$modversion['dirname'] = "profile";
$modversion['dirmoduleadmin'] = "/Frameworks/moduleclasses/moduleadmin";
$modversion['icons16']        = "../../Frameworks/moduleclasses/icons/16";
$modversion['icons32']        = "../../Frameworks/moduleclasses/icons/32";

//about
$modversion['release_date']        = "2015/03/15";
$modversion["module_website_url"]  = "http://www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["module_status"]       = "Beta 1";
$modversion['min_php']             = "5.3.7";
$modversion['min_xoops']           = "2.5.7";
$modversion['min_admin']           = "1.1";
$modversion['min_db']              = array( 'mysql' => "5.0.7", 'mysqli' => "5.0.7" );

// Admin menu
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Scripts to run upon installation or update
$modversion['onInstall'] = "include/install.php";
$modversion['onUpdate'] = "include/update.php";

// Menu
$modversion['hasMain'] = 1;
if ($GLOBALS['xoopsUser']) {
    $modversion['sub'][1]['name'] = _MI_PROFILE_EDITACCOUNT;
    $modversion['sub'][1]['url'] = "edituser.php";
    $modversion['sub'][2]['name'] = _MI_PROFILE_PAGE_SEARCH;
    $modversion['sub'][2]['url'] = "search.php";
    $modversion['sub'][3]['name'] = _MI_PROFILE_CHANGEPASS;
    $modversion['sub'][3]['url'] = "changepass.php";
}

// Mysql file
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][1] = "profile_category";
$modversion['tables'][2] = "profile_profile";
$modversion['tables'][3] = "profile_field";
$modversion['tables'][4] = "profile_visibility";
$modversion['tables'][5] = "profile_regstep";

// Templates
$i = 1;
$modversion['templates'][$i]['file'] = "profile_admin_categorylist.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_admin_fieldlist.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_admin_steplist.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_admin_visibility.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_breadcrumbs.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_form.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_userinfo.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_search.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_results.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_register.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_changepass.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_editprofile.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_userform.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_avatar.tpl";
$modversion['templates'][$i]['description'] = "";
$i++;
$modversion['templates'][$i]['file'] = "profile_email.tpl";
$modversion['templates'][$i]['description'] = "";
unset($i);

$i = 1;
// Config items
$modversion['config'][$i]['name'] = "profile_search";
$modversion['config'][$i]['title'] = "_MI_PROFILE_SEARCH";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "yesno";
$modversion['config'][$i]['valuetype'] = "int";
$modversion['config'][$i]['default'] = 1;
$i++;
// Config Recapcha private api key
$modversion['config'][$i]['name'] = "captcha_disabled";
$modversion['config'][$i]['title'] = "_MI_PROFILE_CAPTCHA_DISABLED";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "yesno";
$modversion['config'][$i]['valuetype'] = "int";
$modversion['config'][$i]['default'] = 0;
$i++;
// Config Recapcha private api key
$modversion['config'][$i]['name'] = "captcha_name";
$modversion['config'][$i]['title'] = "_MI_PROFILE_CAPTCHA_NAME";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "textbox";
$modversion['config'][$i]['valuetype'] = "text";
$modversion['config'][$i]['default'] = "xoopscaptcha";
$i++;
// Config Recapcha private api key
$modversion['config'][$i]['name'] = "captcha_mode";
$modversion['config'][$i]['title'] = "_MI_PROFILE_CAPTCHA_MODE";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "select";
$modversion['config'][$i]['valuetype'] = "text";
$modversion['config'][$i]['default'] = "text";
$modversion['config'][$i]['options'] = array(_MI_PROFILE_CAPTCHA_MODE_TEXT => 'text', 
											 _MI_PROFILE_CAPTCHA_MODE_IMAGE => 'image', 
											 _MI_PROFILE_CAPTCHA_MODE_RECAPTCHA => 'recaptcha');
$i++;
// Config Recapcha private api key
$modversion['config'][$i]['name'] = "captcha_skipmember";
$modversion['config'][$i]['title'] = "_MI_PROFILE_CAPTCHA_SKIPMEMBER";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "yesno";
$modversion['config'][$i]['valuetype'] = "int";
$modversion['config'][$i]['default'] = 1;
$i++;
// Config Recapcha private api key
$modversion['config'][$i]['name'] = "captcha_maxattempts";
$modversion['config'][$i]['title'] = "_MI_PROFILE_CAPTCHA_MAXATTEMPTS";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "textbox";
$modversion['config'][$i]['valuetype'] = "text";
$modversion['config'][$i]['default'] = 10;
$i++;
// Config Recapcha private api key
$modversion['config'][$i]['name'] = "recaptcha_private_apikey";
$modversion['config'][$i]['title'] = "_MI_PROFILE_RECAPTCHA_PRIVATE_APIKEY";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "textbox";
$modversion['config'][$i]['valuetype'] = "text";
$modversion['config'][$i]['default'] = "";
$i++;
// Config Recapcha public api key
$modversion['config'][$i]['name'] = "recaptcha_public_apikey";
$modversion['config'][$i]['title'] = "_MI_PROFILE_RECAPTCHA_PUBLIC_APIKEY";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "textbox";
$modversion['config'][$i]['valuetype'] = "text";
$modversion['config'][$i]['default'] = "";
$i++;
// Config Recapcha type
$modversion['config'][$i]['name'] = "recaptcha_theme";
$modversion['config'][$i]['title'] = "_MI_PROFILE_RECAPTCHA_THEME";
$modversion['config'][$i]['description'] = "";
$modversion['config'][$i]['formtype'] = "select";
$modversion['config'][$i]['valuetype'] = "text";
$modversion['config'][$i]['default'] = "white";
$modversion['config'][$i]['options'] = array(_MI_PROFILE_RECAPTCHA_THEME_RED => 'red', 
											 _MI_PROFILE_RECAPTCHA_THEME_WHITE => 'white', 
											 _MI_PROFILE_RECAPTCHA_THEME_BLACKGLASS => 'blackglass', 
											 _MI_PROFILE_RECAPTCHA_THEME_CLEAN => 'clean', 
											 _MI_PROFILE_RECAPTCHA_THEME_CUSTOM => 'custom');
unset($i);